# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#        C O R U M C O R E
#    Archivo de configuración
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Límite del countdown, es decir, hasta cuándo contará. Hora en formato 24h.
# Formato: dd/MM/yyyy HH:mm (por ejemplo: 31/03/2022 23:59
countdown-limit: "31/03/2022 23:59"