name: CorumCore
authors: [NotEugenio_, BetTD]
version: 1.3.1
website: https://github.com/eugeniodevv/corumcore
main: wtf.eugenio.corumcore.CorumCore
depend: [PlaceholderAPI, TitleManager]
commands:
  cc:
    description: Comando principal de CorumCore
    aliases: [corumcore, corum]
    permission: corum.admin
  vidas:
    description: Visualizar vidas restantes
    aliases: [lifes]
  gamemode:
    description: Cambiar modo de juego
    aliases: [gm, gmc, gms, gma, gmsp]
    permission: corum.gamemode
permissions:
  corum.*:
    description: Absolutamente todo
    default: false
    children:
      corum.admin: true
      corum.gamemode: true
  corum.admin:
    description: Acceso a comandos administrativos
    default: op
  corum.gamemode:
    description: Acceso a comandos de gamemode
    default: op